- name: docker build and push
  hosts: localhost
  tasks:
    - name: Build Docker Image
      command: docker build -t calculator.jar .
      args:
        chdir: /var/lib/jenkins/workspace/SPE_Project

    - name: tag image
      command: docker tag calculator.jar tathagat10/calculator:latest

#    - name: Log in to Docker Hub
#      community.docker.docker_login:
#        registry_url: https://index.docker.io/v1/
#        username: tathagat10
#        password: lmandnjr10

    - name: push image
      command: docker push tathagat10/calculator:latest
